"""Model loading service for the complete MLflow serving pipeline."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from threading import Lock
from typing import ClassVar, Protocol, TypeVar, cast

import mlflow
import mlflow.sklearn as mlflow_sklearn
import numpy as np
import numpy.typing as npt
import pandas as pd
from mlflow import MlflowClient
from mlflow.exceptions import MlflowException
from src.api.schemas import ChurnPredictionRequest
from src.api.settings import ApiSettings
from src.training.preprocessing import MODEL_FEATURE_COLUMNS

LOGGER = logging.getLogger(__name__)
_SingletonInstanceT = TypeVar("_SingletonInstanceT")


class ModelLoadError(RuntimeError):
    """Raised when the promoted model cannot be loaded safely."""


class SingletonMeta(type):
    """Lazy, thread-safe Singleton metaclass.

    The first construction call creates the object. Later construction calls for
    the same class return that same object, which keeps one loaded model service
    per application process.
    """

    _instances: ClassVar[dict[type, object]] = {}
    _lock: ClassVar[Lock] = Lock()

    def __call__(
        cls: type[_SingletonInstanceT],
        *args: object,
        **kwargs: object,
    ) -> _SingletonInstanceT:
        """Return the existing instance or create it on first use."""

        if cls not in SingletonMeta._instances:
            with SingletonMeta._lock:
                if cls not in SingletonMeta._instances:
                    SingletonMeta._instances[cls] = super().__call__(*args, **kwargs)
        return cast(_SingletonInstanceT, SingletonMeta._instances[cls])


class PredictivePipeline(Protocol):
    """Small protocol for the trained scikit-learn pipeline used by the API."""

    def predict(self, features: pd.DataFrame) -> npt.NDArray[np.integer]:
        """Return predicted classes for the provided feature frame."""
        ...

    def predict_proba(self, features: pd.DataFrame) -> npt.NDArray[np.floating]:
        """Return class probabilities when the estimator supports them."""
        ...


@dataclass(frozen=True, slots=True)
class LoadedModelInfo:
    """Non-sensitive lineage for the loaded model version."""

    model_name: str
    model_alias: str
    model_version: str | None
    run_id: str | None
    data_version: str | None
    git_commit: str | None
    model_uri: str


@dataclass(frozen=True, slots=True)
class Prediction:
    """Prediction generated by the complete trained pipeline."""

    predicted_class: int
    churn_probability: float | None


class ChampionModelService(metaclass=SingletonMeta):
    """Loads and serves predictions from the promoted MLflow pipeline."""

    def __init__(self, settings: ApiSettings) -> None:
        self._settings = settings
        self._pipeline: PredictivePipeline | None = None
        self._info: LoadedModelInfo | None = None

    @property
    def is_loaded(self) -> bool:
        """Return whether the champion model has already been loaded."""

        return self._pipeline is not None and self._info is not None

    @property
    def info(self) -> LoadedModelInfo:
        """Return loaded model metadata."""

        if self._info is None:
            raise ModelLoadError("Model metadata is unavailable before startup load")
        return self._info

    def load(self) -> None:
        """Load the champion model during FastAPI lifespan startup."""

        if self.is_loaded:
            return
        mlflow.set_tracking_uri(self._settings.tracking_uri)
        try:
            pipeline = mlflow_sklearn.load_model(self._settings.model_uri)
            model_version = _load_model_version(self._settings)
        except Exception as error:
            raise ModelLoadError(
                "Cannot load serving model "
                f"model={self._settings.model_name} "
                f"alias={self._settings.model_alias}"
            ) from error

        self._pipeline = pipeline
        self._info = _build_loaded_model_info(self._settings, model_version)
        LOGGER.info(
            "serving_model_loaded model=%s alias=%s version=%s",
            self._info.model_name,
            self._info.model_alias,
            self._info.model_version,
        )

    def predict(self, request: ChurnPredictionRequest) -> Prediction:
        """Run one validated request through the complete trained pipeline."""

        if self._pipeline is None:
            raise ModelLoadError("Model pipeline is unavailable before startup load")
        features = pd.DataFrame([request.model_dump()], columns=MODEL_FEATURE_COLUMNS)
        predicted_class = int(self._pipeline.predict(features)[0])
        probability = _predict_churn_probability(self._pipeline, features)
        return Prediction(
            predicted_class=predicted_class,
            churn_probability=probability,
        )


def _load_model_version(settings: ApiSettings):
    client = MlflowClient()
    try:
        return client.get_model_version_by_alias(
            settings.model_name,
            settings.model_alias,
        )
    except MlflowException:
        return None


def _build_loaded_model_info(
    settings: ApiSettings,
    model_version,
) -> LoadedModelInfo:
    if model_version is None:
        return LoadedModelInfo(
            model_name=settings.model_name,
            model_alias=settings.model_alias,
            model_version=None,
            run_id=None,
            data_version=None,
            git_commit=None,
            model_uri=settings.model_uri,
        )
    tags = dict(model_version.tags or {})
    return LoadedModelInfo(
        model_name=settings.model_name,
        model_alias=settings.model_alias,
        model_version=str(model_version.version),
        run_id=model_version.run_id,
        data_version=tags.get("data_version"),
        git_commit=tags.get("git_commit"),
        model_uri=settings.model_uri,
    )


def _predict_churn_probability(
    pipeline: PredictivePipeline,
    features: pd.DataFrame,
) -> float | None:
    if not hasattr(pipeline, "predict_proba"):
        return None
    probabilities = pipeline.predict_proba(features)
    return float(probabilities[0][1])
